# Take high dimensional dataset & apply PCA - specify no. of components & also variance to be retained

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('nndb_flat.csv')
data

ID                       FoodGroup                ShortDescrip  \
0      1001          Dairy and Egg Products            BUTTER,WITH SALT   
1      1002          Dairy and Egg Products    BUTTER,WHIPPED,WITH SALT   
2      1003          Dairy and Egg Products        BUTTER OIL,ANHYDROUS   
3      1004          Dairy and Egg Products                 CHEESE,BLUE   
4      1005          Dairy and Egg Products                CHEESE,BRICK   
...     ...                             ...                         ...   
8613  83110  Finfish and Shellfish Products             MACKEREL,SALTED   
8614  90240  Finfish and Shellfish Products  SCALLOP,(BAY&SEA),CKD,STMD   
8615  90480                          Sweets                  SYRUP,CANE   
8616  90560  Finfish and Shellfish Products                   SNAIL,RAW   
8617  93600  Finfish and Shellfish Products            TURTLE,GREEN,RAW   

                                                Descrip CommonName MfgName  \
0                                        Butter, salted        NaN     NaN   
1                            Butter, whipped, with salt        NaN     NaN   
2                                 Butter oil, anhydrous        NaN     NaN   
3                                          Cheese, blue        NaN     NaN   
4                                         Cheese, brick        NaN     NaN   
...                                                 ...        ...     ...   
8613                             Fish, mackerel, salted        NaN     NaN   
8614  Mollusks, scallop, (bay and sea), cooked, steamed        NaN     NaN   
8615                                        Syrup, Cane        NaN     NaN   
8616                               Mollusks, snail, raw        NaN     NaN   
8617                                 Turtle, green, raw        NaN     NaN   

     ScientificName  Energy_kcal  Protein_g  Fat_g  ...  Folate_USRDA  \
0               NaN        717.0       0.85  81.11  ...        0.0075   
1               NaN        717.0       0.85  81.11  ...        0.0075   
2               NaN        876.0       0.28  99.48  ...        0.0000   
3               NaN        353.0      21.40  28.74  ...        0.0900   
4               NaN        371.0      23.24  29.68  ...        0.0500   
...             ...          ...        ...    ...  ...           ...   
8613            NaN        305.0      18.50  25.10  ...        0.0375   
8614            NaN        111.0      20.54   0.84  ...        0.0500   
8615            NaN        269.0       0.00   0.00  ...        0.0000   
8616            NaN         90.0      16.10   1.40  ...        0.0150   
8617            NaN         89.0      19.80   0.50  ...        0.0375   

      Niacin_USRDA  Riboflavin_USRDA  Thiamin_USRDA  Calcium_USRDA  \
0         0.002625          0.026154       0.004167       0.020000   
1         0.002625          0.026154       0.004167       0.020000   
2         0.000188          0.003846       0.000833       0.003333   
3         0.063500          0.293846       0.024167       0.440000   
4         0.007375          0.270000       0.011667       0.561667   
...            ...               ...            ...            ...   
8613      0.206250          0.146154       0.016667       0.055000   
8614      0.067250          0.018462       0.010000       0.008333   
8615      0.006250          0.046154       0.108333       0.010833   
8616      0.087500          0.092308       0.008333       0.008333   
8617      0.068750          0.115385       0.100000       0.098333   

      Copper_USRDA  Magnesium_USRDA  Phosphorus_USRDA  Selenium_USRDA  \
0         0.000000         0.004762          0.034286        0.018182   
1         0.000018         0.004762          0.032857        0.018182   
2         0.000001         0.000000          0.004286        0.000000   
3         0.000044         0.054762          0.552857        0.263636   
4         0.000027         0.057143          0.644286        0.263636   
...            

In [8]:
data.isnull().sum()

ID                     0
FoodGroup              0
ShortDescrip           0
Descrip                0
CommonName          7555
MfgName             7058
ScientificName      7886
Energy_kcal            0
Protein_g              0
Fat_g                  0
Carb_g                 0
Sugar_g                0
Fiber_g                0
VitA_mcg               0
VitB6_mg               0
VitB12_mcg             0
VitC_mg                0
VitE_mg                0
Folate_mcg             0
Niacin_mg              0
Riboflavin_mg          0
Thiamin_mg             0
Calcium_mg             0
Copper_mcg             0
Iron_mg                0
Magnesium_mg           0
Manganese_mg           0
Phosphorus_mg          0
Selenium_mcg           0
Zinc_mg                0
VitA_USRDA             0
VitB6_USRDA            0
VitB12_USRDA           0
VitC_USRDA             0
VitE_USRDA             0
Folate_USRDA           0
Niacin_USRDA           0
Riboflavin_USRDA       0
Thiamin_USRDA          0
Calcium_USRDA          0


In [10]:
data.dtypes

ID                    int64
FoodGroup            object
ShortDescrip         object
Descrip              object
CommonName           object
MfgName              object
ScientificName       object
Energy_kcal         float64
Protein_g           float64
Fat_g               float64
Carb_g              float64
Sugar_g             float64
Fiber_g             float64
VitA_mcg            float64
VitB6_mg            float64
VitB12_mcg          float64
VitC_mg             float64
VitE_mg             float64
Folate_mcg          float64
Niacin_mg           float64
Riboflavin_mg       float64
Thiamin_mg          float64
Calcium_mg          float64
Copper_mcg          float64
Iron_mg             float64
Magnesium_mg        float64
Manganese_mg        float64
Phosphorus_mg       float64
Selenium_mcg        float64
Zinc_mg             float64
VitA_USRDA          float64
VitB6_USRDA         float64
VitB12_USRDA        float64
VitC_USRDA          float64
VitE_USRDA          float64
Folate_USRDA        

In [13]:
import numpy as np

In [16]:
x= data.drop(['ID','FoodGroup','ShortDescrip','Descrip','CommonName','MfgName','ScientificName',], axis=1)

In [17]:
x

Energy_kcal  Protein_g  Fat_g  Carb_g  Sugar_g  Fiber_g  VitA_mcg  \
0           717.0       0.85  81.11    0.06     0.06      0.0     684.0   
1           717.0       0.85  81.11    0.06     0.06      0.0     684.0   
2           876.0       0.28  99.48    0.00     0.00      0.0     840.0   
3           353.0      21.40  28.74    2.34     0.50      0.0     198.0   
4           371.0      23.24  29.68    2.79     0.51      0.0     292.0   
...           ...        ...    ...     ...      ...      ...       ...   
8613        305.0      18.50  25.10    0.00     0.00      0.0      47.0   
8614        111.0      20.54   0.84    5.41     0.00      0.0       2.0   
8615        269.0       0.00   0.00   73.14    73.20      0.0       0.0   
8616         90.0      16.10   1.40    2.00     0.00      0.0      30.0   
8617         89.0      19.80   0.50    0.00     0.00      0.0      30.0   

      VitB6_mg  VitB12_mcg  VitC_mg  ...  Folate_USRDA  Niacin_USRDA  \
0        0.003        0.17      0.0  ...        0.0075      0.002625   
1        0.003        0.13      0.0  ...        0.0075      0.002625   
2        0.001        0.01      0.0  ...        0.0000      0.000188   
3        0.166        1.22      0.0  ...        0.0900      0.063500   
4        0.065        1.26      0.0  ...        0.0500      0.007375   
...        ...         ...      ...  ...           ...           ...   
8613     0.410       12.00      0.0  ...        0.0375      0.206250   
8614     0.112        2.15      0.0  ...        0.0500      0.067250   
8615     0.000        0.00      0.0  ...        0.0000      0.006250   
8616     0.130        0.50      0.0  ...        0.0150      0.087500   
8617     0.120        1.00      0.0  ...        0.0375      0.068750   

      Riboflavin_USRDA  Thiamin_USRDA  Calcium_USRDA  Copper_USRDA  \
0             0.026154       0.004167       0.020000      0.000000   
1             0.026154       0.004167       0.020000      0.000018   
2             0.003846       0.000833       0.003333      0.000001   
3             0.293846       0.024167       0.440000      0.000044   
4             0.270000       0.011667       0.561667      0.000027   
...                ...            ...            ...           ...   
8613          0.146154       0.016667       0.055000      0.000111   
8614          0.018462       0.010000       0.008333      0.000037   
8615          0.046154       0.108333       0.010833      0.000022   
8616          0.092308       0.008333       0.008333      0.000444   
8617          0.115385       0.100000       0.098333      0.000278   

      Magnesium_USRDA  Phosphorus_USRDA  Selenium_USRDA  Zinc_USRDA  
0            0.004762          0.034286        0.018182    0.008182  
1            0.004762          0.032857        0.018182    0.004545  
2            0.000000          0.004286        0.000000    0.000909  
3            0.054762          0.552857        0.263636    0.241818  
4            0.057143          0.644286        0.263636    0.236364  
...               ...               ...             ...         ...  
8613         0.142857          0.362857        1.334545    0.100000  
8614         0.088095          0.608571        0.394545    0.140909  
8615         0.023810          0.011429        0.012727    0.017273  
8616         0.595238          0.388571        0.498182    0.090909  
8617         0.047619          0.257143        0.305455    0.090909  

[8618 rows x 38 columns]

In [18]:
x.isnull().sum()

Energy_kcal         0
Protein_g           0
Fat_g               0
Carb_g              0
Sugar_g             0
Fiber_g             0
VitA_mcg            0
VitB6_mg            0
VitB12_mcg          0
VitC_mg             0
VitE_mg             0
Folate_mcg          0
Niacin_mg           0
Riboflavin_mg       0
Thiamin_mg          0
Calcium_mg          0
Copper_mcg          0
Iron_mg             0
Magnesium_mg        0
Manganese_mg        0
Phosphorus_mg       0
Selenium_mcg        0
Zinc_mg             0
VitA_USRDA          0
VitB6_USRDA         0
VitB12_USRDA        0
VitC_USRDA          0
VitE_USRDA          0
Folate_USRDA        0
Niacin_USRDA        0
Riboflavin_USRDA    0
Thiamin_USRDA       0
Calcium_USRDA       0
Copper_USRDA        0
Magnesium_USRDA     0
Phosphorus_USRDA    0
Selenium_USRDA      0
Zinc_USRDA          0
dtype: int64

In [25]:
data['Fiber_g'].head(20)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.2
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
Name: Fiber_g, dtype: float64

In [30]:
x['Fiber_g']=x['Fiber_g'].replace(0.0,x['Fiber_g'].mean())

In [31]:
x.head()

Energy_kcal  Protein_g  Fat_g  Carb_g  Sugar_g   Fiber_g  VitA_mcg  \
0        717.0       0.85  81.11    0.06     0.06  2.023242     684.0   
1        717.0       0.85  81.11    0.06     0.06  2.023242     684.0   
2        876.0       0.28  99.48    0.00     0.00  2.023242     840.0   
3        353.0      21.40  28.74    2.34     0.50  2.023242     198.0   
4        371.0      23.24  29.68    2.79     0.51  2.023242     292.0   

   VitB6_mg  VitB12_mcg  VitC_mg  ...  Folate_USRDA  Niacin_USRDA  \
0     0.003        0.17      0.0  ...        0.0075      0.002625   
1     0.003        0.13      0.0  ...        0.0075      0.002625   
2     0.001        0.01      0.0  ...        0.0000      0.000188   
3     0.166        1.22      0.0  ...        0.0900      0.063500   
4     0.065        1.26      0.0  ...        0.0500      0.007375   

   Riboflavin_USRDA  Thiamin_USRDA  Calcium_USRDA  Copper_USRDA  \
0          0.026154       0.004167       0.020000      0.000000   
1          0.026154       0.004167       0.020000      0.000018   
2          0.003846       0.000833       0.003333      0.000001   
3          0.293846       0.024167       0.440000      0.000044   
4          0.270000       0.011667       0.561667      0.000027   

   Magnesium_USRDA  Phosphorus_USRDA  Selenium_USRDA  Zinc_USRDA  
0         0.004762          0.034286        0.018182    0.008182  
1         0.004762          0.032857        0.018182    0.004545  
2         0.000000          0.004286        0.000000    0.000909  
3         0.054762          0.552857        0.263636    0.241818  
4         0.057143          0.644286        0.263636    0.236364  

[5 rows x 38 columns]

In [32]:
x['VitC_mg']=x['VitC_mg'].replace(0.0,x['VitC_mg'].mean())

In [33]:
x.head()

Energy_kcal  Protein_g  Fat_g  Carb_g  Sugar_g   Fiber_g  VitA_mcg  \
0        717.0       0.85  81.11    0.06     0.06  2.023242     684.0   
1        717.0       0.85  81.11    0.06     0.06  2.023242     684.0   
2        876.0       0.28  99.48    0.00     0.00  2.023242     840.0   
3        353.0      21.40  28.74    2.34     0.50  2.023242     198.0   
4        371.0      23.24  29.68    2.79     0.51  2.023242     292.0   

   VitB6_mg  VitB12_mcg   VitC_mg  ...  Folate_USRDA  Niacin_USRDA  \
0     0.003        0.17  7.925377  ...        0.0075      0.002625   
1     0.003        0.13  7.925377  ...        0.0075      0.002625   
2     0.001        0.01  7.925377  ...        0.0000      0.000188   
3     0.166        1.22  7.925377  ...        0.0900      0.063500   
4     0.065        1.26  7.925377  ...        0.0500      0.007375   

   Riboflavin_USRDA  Thiamin_USRDA  Calcium_USRDA  Copper_USRDA  \
0          0.026154       0.004167       0.020000      0.000000   
1          0.026154       0.004167       0.020000      0.000018   
2          0.003846       0.000833       0.003333      0.000001   
3          0.293846       0.024167       0.440000      0.000044   
4          0.270000       0.011667       0.561667      0.000027   

   Magnesium_USRDA  Phosphorus_USRDA  Selenium_USRDA  Zinc_USRDA  
0         0.004762          0.034286        0.018182    0.008182  
1         0.004762          0.032857        0.018182    0.004545  
2         0.000000          0.004286        0.000000    0.000909  
3         0.054762          0.552857        0.263636    0.241818  
4         0.057143          0.644286        0.263636    0.236364  

[5 rows x 38 columns]

In [34]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
x_scaled = ss.fit_transform(x)

In [35]:
x_scaled

array([[7.94900222e-01, 9.62409420e-03, 8.11100000e-01, ...,
        2.41984271e-03, 5.21648409e-04, 9.89554700e-04],
       [7.94900222e-01, 9.62409420e-03, 8.11100000e-01, ...,
        2.31901593e-03, 5.21648409e-04, 5.49752611e-04],
       [9.71175166e-01, 3.17028986e-03, 9.94800000e-01, ...,
        3.02480339e-04, 0.00000000e+00, 1.09950522e-04],
       ...,
       [2.98226164e-01, 0.00000000e+00, 0.00000000e+00, ...,
        8.06614237e-04, 3.65153886e-04, 2.08905992e-03],
       [9.97782705e-02, 1.82291667e-01, 1.40000000e-02, ...,
        2.74248840e-02, 1.42931664e-02, 1.09950522e-02],
       [9.86696231e-02, 2.24184783e-01, 5.00000000e-03, ...,
        1.81488203e-02, 8.76369327e-03, 1.09950522e-02]])

In [36]:
from sklearn.decomposition import PCA
# specify number of PC
p = PCA(n_components= 2)

In [37]:
p_comp = p.fit_transform(x_scaled)

In [38]:
p_comp

array([[ 0.10955733,  0.86334871],
       [ 0.1096424 ,  0.86333073],
       [ 0.20431378,  1.09364515],
       ...,
       [ 0.63106933, -0.33164242],
       [-0.22322184, -0.05057902],
       [-0.29065077, -0.06227756]])

In [39]:
p.explained_variance_ratio_

array([0.4689172 , 0.23017981])

In [40]:
# variance to be retained
p2 = PCA(.98)

In [41]:
p2.fit_transform(x_scaled)

array([[ 1.09557327e-01,  8.63348712e-01, -3.01520303e-01, ...,
         1.78013027e-02, -2.10842720e-02, -2.77910350e-02],
       [ 1.09642398e-01,  8.63330734e-01, -3.01364372e-01, ...,
         1.86442021e-02, -2.10625208e-02, -2.66533881e-02],
       [ 2.04313776e-01,  1.09364515e+00, -3.50809941e-01, ...,
         2.34530288e-02, -2.73702184e-02, -3.23606954e-02],
       ...,
       [ 6.31069329e-01, -3.31642424e-01, -2.30439181e-01, ...,
        -2.68146668e-03, -2.06092802e-02,  1.43361380e-02],
       [-2.23221841e-01, -5.05790171e-02,  2.17396617e-01, ...,
        -7.24434355e-02, -1.99283180e-02,  2.85941117e-02],
       [-2.90650769e-01, -6.22775620e-02,  5.57671737e-02, ...,
         1.06962064e-03,  1.96888969e-02,  1.22465323e-02]])

In [42]:
p2.n_components_

14

In [45]:
p1 = PCA(n_components= 4)

In [46]:
p_comp1 = p1.fit_transform(x_scaled)
p_comp1

array([[ 0.10955733,  0.86334871, -0.30152032, -0.0837194 ],
       [ 0.1096424 ,  0.86333073, -0.30136439, -0.08388276],
       [ 0.20431378,  1.09364514, -0.35080996, -0.09467346],
       ...,
       [ 0.63106933, -0.33164242, -0.23043918,  0.39957835],
       [-0.22322184, -0.05057901,  0.21739664, -0.09994453],
       [-0.29065077, -0.06227756,  0.05576718,  0.03192825]])

In [47]:
p1.explained_variance_ratio_

array([0.4689172 , 0.23017981, 0.0960077 , 0.05154465])

In [48]:
p1.n_components_

4